# add mgo.v2 library for centos7_golang1.10.3

FROM iotdog/centos7_go1.10.3:latest

RUN go get -u gopkg.in/mgo.v2
RUN go get -u gopkg.in/mgo.v2/bson
RUN go get -u golang.org/x/crypto/...
RUN go get -u golang.org/x/tools/...